### PR TITLE
Allow defining remote repo

### PR DESCRIPTION
**Pull request by foxriver76**
- don't no why compiling the typescript gives such a big diff 🤷

### CODE REVIEW

**Comment by AlCalzone** [comment]
Line endings probably

**Comment by foxriver76** [comment]
Hm the releaseconfig  approach is suboptimal, because it will have different remote name for every dev, should be a cli arg.

**Comment by foxriver76** [comment]
also not really sure why the first hypens are needed while testing I hadn't any issues, is it only a windows problem? So basically I tried to stick to your `-c` option for the config file.

**Comment by AlCalzone** [comment]
AFAIK they are necessary for options with double dashes. Without the extra `--`, `npm` thinks the options are for itself, not the invoked command.

**Review by AlCalzone — APPROVED** [review]
Thanks!

**Pull request merged**
